services:
  dnmonster:
    image: amouat/dnmonster:latest
    ports:
      - "8085:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  identidock:
    build: .
    ports:
      - "9090:9090"
      - "9191:9191"
    environment:
      - ENV=PROD
    depends_on:
      - dnmonster
      - redis