services:
  dnmonster:
    image: amouat/dnmonster:latest
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENV=DEV
    volumes:
      - ./app:/app
    depends_on:
      - dnmonster
      - redis